apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # indica la ruta donde estan todos los archivos .yml y ejecuta todos de una vez
build:
  # local:
  #  push: false # No pushear a docker hub las imagenes
  googleCloudBuild:
    projectId: ticketing-dev-381622
  artifacts:
    - image: us.gcr.io/ticketing-dev-381622/auth
      context: auth
      docker: # va a crear una imagen de docker
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' # escuchar cambios en archivos de extension ts
            dest: . # indica la carpeta que se va usar para almacenar la aplicacion en el contenedor
