apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # indica la ruta donde estan todos los archivos .yml y ejecuta todos de una vez
build:
  local:
    push: false # No pushear a docker hub las imagenes
  artifacts:
    - image: nrv2391/ticketing-auth
      context: auth
      docker: # va a crear una imagen de docker
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # escuchar cambios en archivos de extension ts
            dest: . # indica la carpeta que se va usar para almacenar la aplicacion en el contenedor
    - image: nrv2391/ticketing-client
      context: client
      docker: # va a crear una imagen de docker
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js" # escuchar cambios en archivos de extension ts
            dest: . # indica la carpeta que se va usar para almacenar la aplicacion en el contenedor
    - image: nrv2391/ticketing-tickets
      context: tickets
      docker: # va a crear una imagen de docker
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # escuchar cambios en archivos de extension ts
            dest: . # indica la carpeta que se va usar para almacenar la aplicacion en el contenedor
    - image: nrv2391/ticketing-orders
      context: orders
      docker: # va a crear una imagen de docker
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts" # escuchar cambios en archivos de extension ts
            dest: . # indica la carpeta que se va usar para almacenar la aplicacion en el contenedor
    - image: nrv2391/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: nrv2391/ticketing-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
