apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration # este nombre auth coincide con el nombre app de matchLabels del deployment, es para indicar los pods que el deployment va administrar o usar
    spec:
      containers:
        - name: expiration
          image: nrv2391/ticketing-expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name # generar un nombre aleatorio para el clientid. En nats los clientid siempre
                    # deben ser unicos.
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv


