
name: tests-payments

on: # cuando se crea un pull request entonces las acciones de github se ejecutan
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
